### ISSUE TITLE
packed bpmnlint configuration

### ISSUE THREAD

**Issue by MarwAjmi** [bpmn-io/bpmn-js-bpmnlint#12]
When I'm trying to execute this command 

bpmnlint-pack-config -c .bpmnlintrc -o bundled-config.js
i got this error 
![image](https://user-images.githubusercontent.com/37660440/61628918-724b4080-ac7b-11e9-934e-7c3b4cf11479.png)

**Comment by nikku** [comment]
Addressed via https://forum.bpmn.io/t/bpmnlint-configure-lint-rules/3681 I guess.
