### ISSUE TITLE
Schema errors not displayed

### ISSUE THREAD

**Issue by AndreyOsipkov** [bpmn-io/bpmn-js-bpmnlint#22]
Hello!
__Describe the Bug__

Schema errors not displayed

__Steps to Reproduce__

1. connected as indicated in the documentation
2. created a config and connected
3. there are no changes in the diagram

`import { Linter } from 'bpmnlint';
import linterConfig from './packed-config';
import lintModule from 'bpmn-js-bpmnlint';
import Modeler from 'bpmn-js/lib/Modeler';`

![image](https://user-images.githubusercontent.com/34154796/79842189-24f23000-83c1-11ea-9ab9-f888d8712fb2.png)

no change
![image](https://user-images.githubusercontent.com/34154796/79842334-57039200-83c1-11ea-89ae-1f5936cc712c.png)

if you remove the style of stretching in height, a button appears
![image](https://user-images.githubusercontent.com/34154796/79842759-ef017b80-83c1-11ea-9a9d-4692521e147e.png)

__Environment__

- bpmnlint: 6.4.0
- bpmn-js: 6.3.0
- bpmn-js-bpmnlint: 0.14.0

**Comment by nikku** [comment]
What is your expected behavior in your case?

**Comment by AndreyOsipkov** [comment]
expected to get errors on the chart.

additionally connected styles, and bugs appeared 
`@import "~bpmn-js-bpmnlint/dist/assets/css/bpmn-js-bpmnlint.css";`

![image](https://user-images.githubusercontent.com/34154796/79844481-6506e200-83c4-11ea-8bf6-ad2238c8e6af.png)

**Comment by nikku** [comment]
Please share a minimal diagram for which you expect an error / warning to be shown.

**Comment by AndreyOsipkov** [comment]
The error I had was that no errors were shown. Due to the fact that the styles were not pulled. After the styles indicated everything worked. thanks
