### ISSUE TITLE
Default styling of dropdown content's svg elements broken due to flexbox rule

### ISSUE THREAD

**Issue by adroste** [bpmn-io/bpmn-js-bpmnlint#24]
__Describe the Bug__

Error/Warning svgs will auto shrink randomly because `.bjsl-issues` is set to `display: flex`;

Example:
<img width="177" alt="Screenshot 2020-12-13 at 01 32 31" src="https://user-images.githubusercontent.com/18649298/102000093-dc86da00-3ce3-11eb-913f-21779dde7047.png">

__Expected Behavior__

Svg icons should have fixed size.

Example:
<img width="152" alt="Screenshot 2020-12-13 at 01 40 02" src="https://user-images.githubusercontent.com/18649298/102000117-2c65a100-3ce4-11eb-8e69-706f8d5bbd53.png">

__Fix__

I made a PR: #25

**Comment by nikku** [comment]
Thanks for your bug report!

When does that happen? Only with translated, multi line labels I guess? If so, could you provide us with an example that allows us to reproduce the issue?

**Comment by nikku** [comment]
Figured it out. It is the long labels.

**Comment by nikku** [comment]
A simple patch in the HTML, i.e. by duplicating the error description does the trick.

**Comment by nikku** [comment]
Released with `v0.16.0`.
