### ISSUE TITLE
Issues shown twice

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-bpmnlint#3]
Given this config:

```
var LINTER_CONFIG = {
  "extends": "bpmnlint:all",
  "rules": {
    "label-required": 1,
    "start-event-required": 2,
    "end-event-required": 2
  }
};
```

Issues show up twice:

```
{
  category: "error",
  id: "Participant_1t4x716",
  message: "is missing label/name",
  rule: "bpmnlint/label-required"
}, {
  category: "warn",
  id: "Participant_1t4x716",
  message: "is missing label/name",
  rule: "label-required"
}
```

Result:
![image](https://user-images.githubusercontent.com/7633572/45209400-3559a380-b28d-11e8-953e-48c95d77afff.png)

@nikku Shouldn't the inherited one be overridden?

**Comment by nikku** [comment]
This is an error in bpmnlint.

It seems like that inherited rules are not properly overridden,

**Comment by nikku** [comment]
Needs fix via https://github.com/bpmn-io/bpmnlint/issues/20.
