### ISSUE TITLE
Display process lint errors on connected participant

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-bpmnlint#30]
__Is your feature request related to a problem? Please describe__

In collaboration diagrams we usually treat expanded participants like the process it is connected to, interaction wise. With https://github.com/bpmn-io/bpmn-js-bpmnlint/pull/29 merged we have the potential to better support this special case, too.

__Describe the solution you'd like__

* Display process lint errors not on the root but on the visible participant that represents it

__Describe alternatives you've considered__

* Keep existing behavior

__Additional context__

Current behavior (as of `v0.17.0`): Note that the process error is shown on the root, rather than the participant, which would be my expected position to display it.

![capture QDWeit_optimized](https://user-images.githubusercontent.com/58601/114902031-b8fca900-9e15-11eb-8fd6-b02aa3b302fb.gif)

**Comment by nikku** [comment]
Added a failing test case for the scenario mentioned above to the [`process-collaboration` branch](https://github.com/bpmn-io/bpmn-js-bpmnlint/tree/process-collaboration).

**Comment by andreasgeier** [comment]
@nikku Is this the overlay appearance on Linux? The pills look too big, maybe caused by the line break? @MaxTru maybe you can check?

**Comment by nikku** [comment]
The pills look is indeed caused by the multi-line error message. It is not specific to Linux. 

My proposal is to fix that along with https://github.com/bpmn-io/bpmn-js-bpmnlint/pull/31. What do you thing @MaxTru?

**Comment by MaxTru** [comment]
Will do that
