### ISSUE TITLE
how to use i18n?

### ISSUE THREAD

**Issue by tony2y** [bpmn-io/bpmn-js-bpmnlint#38]

**Comment by tony2y** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/38598582/223611643-8466068e-52f3-4227-a8fb-7a4402819a3f.png">

**Comment by tony2y** [comment]
<img width="225" alt="image" src="https://user-images.githubusercontent.com/38598582/223611693-90425113-a8c3-4f18-9dd4-a4eae6bf10c3.png">

**Comment by nikku** [comment]
Consider asking questions [in our forum](https://forum.bpmn.io/).
