### ISSUE TITLE
Error: Cannot resolve config <recommended> from <bpmnlint-plugin-rule>

### ISSUE THREAD

**Issue by tony2y** [bpmn-io/bpmn-js-bpmnlint#39]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/38598582/223760970-8e540691-71a4-479d-8a13-bc0daecafc30.png">

**Comment by tony2y** [comment]
I refer to : https://github.com/bpmn-io/bpmnlint-playground，Then customize the verification rules in my existing projects

Step 1.

npx create-bpmnlint-plugin rule
<img width="305" alt="image" src="https://user-images.githubusercontent.com/38598582/223962550-095c7d41-95c4-4a23-b496-3da44397d8e2.png">

Step 2.

 "plugin:rule/recommended" add .bpmnlintrc
<img width="394" alt="image" src="https://user-images.githubusercontent.com/38598582/223962457-84f56ea9-1c49-4274-be52-43e53ada93a8.png">

Step 3.
carry out ‘npm run dev ’，The following error occurred
![image](https://user-images.githubusercontent.com/38598582/223962772-0119759b-ffb9-49f2-b1a2-71a9fd944522.png)

**Comment by tony2y** [comment]
vue project root directory

**Comment by tony2y** [comment]
Or where does this need to be defined to be used normally in the project

**Comment by tony2y** [comment]
> 在哪里`rule/recommended`定义的？

bpmnlint-plugin-rule directory-index.js

**Comment by tony2y** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/38598582/224005301-32a09fac-57a5-4508-a37c-cb91ce36dbef.png">

**Comment by nikku** [comment]
Does it work in the playground? I.e. does it work if you `npx bpmnlint-playground` in your plug-in folder?

**Comment by tony2y** [comment]
> 它在操场上有效吗？`npx bpmnlint-playground`也就是说，如果您在插件文件夹中，它会起作用吗？

I haven't tried yet, download and run it now
