### ISSUE TITLE
TypeError: ruleFactory is not a function

### ISSUE THREAD

**Issue by jackjtr** [bpmn-io/bpmn-js-bpmnlint#80]
### Describe the Bug

Vite+bpmn-js+bpmn-js-bpmnlint cause runtime error
```
Uncaught (in promise) TypeError: ruleFactory is not a function
    at bpmn-js-bpmnlint.js?v=5597bdc5:188:46
```

### Steps to Reproduce

```
import lintModule from 'bpmn-js-bpmnlint'

...
const modeler = new Modeler({
    container: modelerRef,
    additionalModules: [
      ...,
      lintModule
    ]
  })
...
```

### Expected Behavior

The lint module works

### Environment

- Host (Browser/Node version), if applicable: Chrome, Node v20
- OS: Windows 10
- Library version: 0.22.3

**Comment by nikku** [comment]
The rule you inject is not properly defined. Consider to debug your application to see how a non-function `ruleFactory` [ends up in the app](https://github.com/bpmn-io/bpmnlint/blob/87c0b5d5886ac0926e18c048480e17415544ca3c/lib/linter.js#L98).

**Comment by jackjtr** [comment]
> The rule you inject is not properly defined. Consider to debug your application to see how a non-function `ruleFactory` [ends up in the app](https://github.com/bpmn-io/bpmnlint/blob/87c0b5d5886ac0926e18c048480e17415544ca3c/lib/linter.js#L98).

I am migrating my project from Vue 2 to Vue 3, and changing frontend tool from Vue-CLI to Vite. The project works well before migrating. While `require` syntax is not supported in Vite, maybe it's the reason.
Is there any plan for ES modules? Thanks!

**Comment by barmac** [comment]
Can you provide a codesandbox which reproduces the issue? https://codesandbox.io/

**Comment by jackjtr** [comment]
> Can you provide a [codesandbox](https://codesandbox.io/) which reproduces the issue?

[Link](https://codesandbox.io/p/devbox/bpmn-js-bpmnlint-issue-80-9md7z7)

Open `DevTools` and click `refresh` button, then you will see the error log

**Comment by barmac** [comment]
This is an issue with the code in your project. A rule is always a factory function which returns an object of form `{ check: (node, reporter) => void }` while in the code you shared it's already the object (not a function). Fix:

```diff
- export default {
-   check,
+ export default () => {
+   return {
+     check,
+   }
};
```

**Comment by jackjtr** [comment]
> This is an issue with the code in your project. A rule is always a factory function which returns an object of form `{ check: (node, reporter) => void }` while in the code you shared it's already the object (not a function). Fix:
> 
> ```diff
> - export default {
> -   check,
> + export default () => {
> +   return {
> +     check,
> +   }
> };
> ```

Oh, I see...
Actually I am rarely using `module.exports` and did not realize that it was the problem.
Now it works well after I wrapped the code with `export default function() { ... }`.
Thanks!

**Comment by nikku** [comment]
> Actually I am rarely using module.exports and did not realize that it was the problem.

This was not a problem with `module.exports`, but you defining the rule-factory as an object, not a function. :slightly_smiling_face: 

Happy you were able to fix this, and interesting this worked for you in vue@2.

**Comment by jackjtr** [comment]
> > Actually I am rarely using module.exports and did not realize that it was the problem.
> 
> This was not a problem with `module.exports`, but you defining the rule-factory as an object, not a function. 🙂
> 
> Happy you were able to fix this, and interesting this worked for you in vue@2.

It was `module.exports` in the old project.
I rewrited this file from `CommonJS` to `ESM`. And I thought `module.exports` should be rewrited too, which made the mistake.
